#!/usr/bin/env python

def fizzbuzz(n):
if n % 3 == 0 and n % 5 == 0:
return 'fizzbuzz'
if n % 3 == 0:
return 'fizz'
if n % 5 == 0:
return 'buzz'
else:
return n
for n in xrange(1,20):
print fizzbuzz(n)
